// Auto-generated by .github/workflows/pages.yml on first deploy.
// Edit only if you want to swap backends. The bucket value is a non-secret
// identifier — anyone with the URL can read/write the leaderboard.
window.APP_CONFIG = { mode: 'local' };
