// Auto-generated by .github/workflows/pages.yml on first deploy.
// The url below is a non-secret identifier — anyone with the URL can
// read/write the leaderboard JSON. Acceptable for a small ephemeral app.
window.APP_CONFIG = {
  mode: 'shared',
  provider: 'jsonblob',
  url: 'https://jsonblob.com/api/jsonBlob/019e6017-57fa-72dc-a840-101397db8dda'
};
